spring.application.name=defect_tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/defect_tracker
spring.datasource.username=postgres
spring.datasource.password=root
cors.origin.allowed=http://localhost:5173
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.flyway.locations=classpath:/db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

jwt.secret=cwPiTl3NWAviW3HCkbKYiJYRAjRENWKsC7FEQI0oKLjKF9MnwJ8WW417U8G6FsyUgXZkNFgrmJZNiC3VMwSKpw==
jwt.expiration=18000000
# Forgot Password
#app.frontend.url=http://localhost:5173

# Forgot Password
app.frontend.url=${FRONTEND_URL:http://localhost:5173}


azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING:}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER:def-16b}